### PR TITLE
Fixed bug in logging timestamp; fixes failing test_logging test

### PR DESCRIPTION
**Pull request by kelockhart**

### CODE REVIEW

**Comment by kelockhart** [comment]
Fixes issue #12

**Comment by romanchyla** [comment]
with your changes, the tests are failing - what errors did you try to address? (the original passes on Travis as well as my machine)

**Comment by kelockhart** [comment]
Weird, the tests were failing on my machine *without* fixing this (@spacemansteve's machine too). Here's a line from the logs that are written as part of test_logging (without my fix):
> "asctime": "2017-12-21T17:45:10.fZ", "msecs": 768.7931060791016, "levelname": "WARNING", "process": 14975, "threadName": "MainThread", "filename": "test_init.py", "lineno": 22, "message": "first", "timestamp": "2017-12-21T17:45:10.fZ", "hostname": "adskl.cfa.harvard.edu"}

The fractional seconds in asctime and timestamp are being written as ".f", causing [this line](https://github.com/adsabs/ADSPipelineUtils/blob/master/adsputils/tests/test_init.py#L51) to fail. My fix caused these to be written correctly and allowed the tests to run.

**Comment by romanchyla** [comment]
try to pin point the place where the extrapolation happens; maybe that will
give us a clue why the behavious differes on mac (my python is: '2.7.12
(default, Nov 19 2016, 06:48:10) \n[GCC 5.4.0 20160609])

**Comment by spacemansteve** [comment]
Python on a mac is different.
On my mac:
```
% python --version
Python 2.7.12
>>> time.strftime("%Y-%m-%dT%H:%M:%S.%fZ", time.gmtime())
'2017-12-22T16:18:02.fZ'
```
On adsvm:
```
root@adsvm04:/app# python --version
Python 2.7.12
>>> time.strftime("%Y-%m-%dT%H:%M:%S.%fZ", time.gmtime())
'2017-12-22T16:18:06.%fZ'
```

**Comment by romanchyla** [comment]
i was hesitant because (albeit very small change) it will actually mean doubling the work we do (whether it is 2 x 0.000000000000001s or 2x0.1 i don't know)

but alternative suggests itself and it is a good one, you please change the code to read:

```
datefmt = datefmt.replace('%f', '%03d' % (record.msecs))
return Formatter.formatTime(self, record, datefmt)
```
and would you be so kind to also update adsmutils?

**Comment by kelockhart** [comment]
Ah, that works. I've pushed the commit and will go look at adsmutils.

**Pull request merged**
